name: Label New Issues To Do

on:
  issues:
    types: [opened]
    
permissions:
  issues: write
    
jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Label New Issues To Do
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "To Do"
